# Generated by Django 4.0.4 on 2022-05-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendRest', '0002_c_delete_a_delete_b'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C',
            new_name='Data',
        ),
    ]
